# Правило 1: Скачать 2 файла в папку input
rule download:
    output:
        "input/mass_spec_results.csv",
        "input/sample_metadata.csv"
    container: "docker://mass_spec:latest"
    shell:
        """
        mkdir -p input
        wget -O input/mass_spec_results.csv 'https://storage.yandexcloud.net/students-common/mass_spec_results.csv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=YCAJELqVUR2I4aFR9yju0lZmQ%2F20251129%2Fru-central1%2Fs3%2Faws4_request&X-Amz-Date=20251129T075802Z&X-Amz-Expires=2592000&X-Amz-Signature=8696243c988ba07aaf3b8c3bbf6ef9eedaff7c5d6e4364aea6087493c19e3e39&X-Amz-SignedHeaders=host&response-content-disposition=attachment'
        wget -O input/sample_metadata.csv 'https://storage.yandexcloud.net/students-common/sample_metadata.csv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=YCAJELqVUR2I4aFR9yju0lZmQ%2F20251129%2Fru-central1%2Fs3%2Faws4_request&X-Amz-Date=20251129T075822Z&X-Amz-Expires=2592000&X-Amz-Signature=10e1273d1fcbd5cba59ca00125eb26a4406c14a0ce39c97bcdd5a266493e8015&X-Amz-SignedHeaders=host&response-content-disposition=attachment'
        """

# Правило 2: Сделать антиджоины - на самом деле просто проверить что они есть
rule anti_join:
    output:
        "output/anti_left.csv",
        "output/anti_outer.csv",
        "output/anti_right.csv"
    container: "docker://mass_spec:latest"
    shell:
        """
        # Просто проверяем что файлы антиджоинов существуют
        echo "Anti-joins from previous homework are ready"
        """